본문은 권창현 교수님의 줄리아 책, julia programming for Operations Rsearch를 참고하여 정리하였습니다.
> https://www.softcover.io/read/7b8eb7d0/juliabook2/frontmatter


# Chapter 3. Basic of the Julia Language

이 챕터에서는 기본적인 줄리아 문법을 정리하였다. 
나는 모르는것만 정리할 예정이다!

## 3.1 Vector, Matrix, and Array
matlab같은 언어체계를 가지고 있다고 한다. 

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}	
$$

In [1]:
A = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

Transpose는 다음 두가지가 동일하다!

In [2]:
transpose(A)

3×2 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [3]:
A'

3×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [4]:
B = [1 3 2 ; 3 2 2 ; 1 1 1]
inv(B)

3×3 Array{Float64,2}:
  1.11022e-16   1.0  -2.0
  1.0           1.0  -4.0
 -1.0          -2.0   7.0

In [6]:
a = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [7]:
b = [1.0; 2; 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

경우에 따라 특정 타입으로 정해주어야 할 때가 있다. ```Array```와 ```undef```를 사용함으로써 할 수 있다. 예를 들면 ```Float64```타입이면서 size는 3인 경우 다음과 같이 만들 수 있다. 정수를 넣어주었지만 결과는 Float64에 맞춰서 정의되는 것을 확인 할 수 있다. 

In [8]:
d = Array{Float64}(undef,3)

3-element Array{Float64,1}:
 6.90037052580953e-310
 6.9003705258103e-310 
 6.9003705258111e-310 

In [12]:
d[1] = 1
d[2] = 2
d[3] = 3
d

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

만약 array를 벡터나 메트릭스로 나타내야 한다면,  차원을 명시 적으로 지정하여 배열을 만드는 것이 좋다. 1x3 열 벡터의 경우 다음을 수행해야합니다.

In [16]:
p = Array{Float64}(undef, 1, 3)

1×3 Array{Float64,2}:
 6.90037e-310  6.90037e-310  6.90037e-310

In [17]:
p[1] = 1
p[2] = 2
p[3] = 3
p

1×3 Array{Float64,2}:
 1.0  2.0  3.0

## 3.2 Tuple

어레이타입 데이터는 데이터타입의 쌍이 될 수 있다. 예를 들면, (1,2), (3,4), (5,6)를 어레이로 저장하고 싶다면 다음과 같이 할 수 있다. (이때 타입은 Int64로 정하겠다.)

In [18]:
pairs = Array{Tuple{Int64, Int64}}(undef, 3)

3-element Array{Tuple{Int64,Int64},1}:
 (139665038823432, 139665044104304)
 (139665044104400, 139665044104432)
 (139665044104464, 139665044013840)

In [20]:
pairs[1] = (1,2)
pairs[2] = (3,4)
pairs[3] = (5,6)
pairs

3-element Array{Tuple{Int64,Int64},1}:
 (1, 2)
 (3, 4)
 (5, 6)

임의의 row는 어떻게 하지..?

## 3.3 Indeces and Ranges

array - vector, matrix나 기타 array - 을 range로 사용하기 유용하다. 

In [21]:
a = [10; 20; 30; 40; 50; 60; 70; 80; 90]
a[1:3:9] # 3번째 마다 9번째까지 뽑고 싶을 때

3-element Array{Int64,1}:
 10
 40
 70

In [22]:
a[end-2:end]#끝은 9번쨰 이고, -2이니 7번째 부터 9번쨰 까지 나옴!

3-element Array{Int64,1}:
 70
 80
 90

In [23]:
c = collect(1:2:9) #범위를 정의하고 사용할 수 있음! (index처럼)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [24]:
A= [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [25]:
A[:, 2]  #A[행, 열]

3-element Array{Int64,1}:
 2
 5
 8

In [27]:
A[:, 2:3 ]

3×2 Array{Int64,2}:
 2  3
 5  6
 8  9

## 3.4 Printing Messages
println은 한 줄 씩 프린트 하는 거고, print는 붙어서 나온다!

In [29]:
a = 123.0
println("a is $a, and a-10 is $(a-10)")

a is 123.0, and a-10 is 113.0


In [31]:
using Printf #C의 프린트 함수를 사용할 수 있음
@printf("The %s of a  = %f ", "value", a) #%s: string, %f: floating number, %d: integer


The value of a  = 123.000000 

In [41]:
c = [ 123.12345   ;
       10.983     ;
        1.0932132  ]
for i in 1:length(c)
    println("c[$i] = $(c[i])")
end

println("\n@printf's result is followed\n")
for i in 1:length(c)
    @printf("c[%d] = %7.3f\n", i, c[i])
end

println("\n@sprintf's result is followed\n")
str = @sprintf("The %s of a = %f", "value", a) #string 버전!
println(str)

c[1] = 123.12345
c[2] = 10.983
c[3] = 1.0932132

@printf's result is followed

c[1] = 123.123
c[2] =  10.983
c[3] =   1.093

@sprintf's result is followed

The value of a = 123.000000


## 3.5 Collection, Dictionary, and For-Loop

### Collection and For-Loop

In [43]:
for i in 1:5
    println("This is number $i.")
end

This is number 1.
This is number 2.
This is number 3.
This is number 4.
This is number 5.


In [44]:
for i in 1:5
    if i >= 3
        break
    end
    println("This is number $i.")
end

This is number 1.
This is number 2.


### Dictionary

In [46]:
my_keys = ["Zinedine Zidane", "Magic Johnson", "Yuna Kim"]
my_values = ["football", "basketball", "figure skating"]
d = Dict()
for i in 1:length(my_keys)
    d[my_keys[i]] = my_values[i]
end
d

Dict{Any,Any} with 3 entries:
  "Magic Johnson"   => "basketball"
  "Zinedine Zidane" => "football"
  "Yuna Kim"        => "figure skating"

In [48]:
d["Diego Maradona"] = "football" # add
for (key, value) in d
    println("$key is a $value player.")
end

Magic Johnson is a basketball player.
Zinedine Zidane is a football player.
Diego Maradona is a football player.
Yuna Kim is a figure skating player.


 ### Dictionary - network

In [49]:
links = [ (1,2), (3,4), (4,2) ]
link_costs = [ 5, 13, 8]

link_dict = Dict()

for i in 1:length(links)
    link_dict[ links[i] ] = link_costs[i]
end

link_dict

Dict{Any,Any} with 3 entries:
  (1, 2) => 5
  (4, 2) => 8
  (3, 4) => 13

In [50]:
for (link, cost) in link_dict
    println("Link $link has cost of $cost.")
end

Link (1, 2) has cost of 5.
Link (4, 2) has cost of 8.
Link (3, 4) has cost of 13.


## 3.6 Function

$$
f(x,y) = 3x +y
$$

In [53]:
function f(x, y)
    return 3x + y
end

#or

f(x,y) = 3x+y

f (generic function with 1 method)

In [54]:
println(f(1,3))
println(3 * (f(3,2) + f(5,6)))

6
96


In [55]:
function my_func(n, m)
    a = zeros(n,1)
    b = ones(m, 1)
    return a, b
end
    

my_func (generic function with 1 method)

In [57]:
x, y = my_func(3,2)

([0.0; 0.0; 0.0], [1.0; 1.0])

In [59]:
myfunc(x) = sin(x) + 3*x

println(myfunc(3))

myfunc.([5 10]) # '.' 은 요소 하나하나에 적용한다는 broadcast이다!



9.141120008059866


1×2 Array{Float64,2}:
 14.0411  29.456

## 3.7 Scope of Variables

어떤 프로그래밍 언어에서든 variable이 어디에 적용되는지 이해하는 것은 중요하다.

In [60]:
function f(x)
  return x+2
end

function g(x)
  return 3x+3
end

g (generic function with 1 method)

위와 같은 함수에서 사용된 x는 다른 함수에 다른 scope blocks에서 정의되므로 충돌하지 않는다. 
variable을 처음 정해줄 때 scope에 잘 맞춰 주어야 한다. 밑에 예제는 값이 틀리다!! (~~왜 틀리는거지..? 흠...~~)

In [62]:
function f(x)
  return x+a
end

function run()
  a = 10
  return f(5)
end

run()

128.0

다음처럼 처음 variable은 밖에 위치하게 해줌으로써 parent scop block에 넣어야 한다.

In [63]:
function f(x)
  return x+a
end

function run()
  return f(5)
end

a = 10
run()

15

In [66]:
function f2(x)
  a = 0
  return x+a
end

a = 5
println(f2(1)) # a는 안바뀐다! 
println(a)

#이런 경우들을 조심하자~!

1
5


In [67]:
function f3(x)
  _a = 0 #'_'를 붙여줌으로써 local variable임을 의미하게 해주었다.
  return x + _a
end

a = 5
println(f3(1)) 
println(a)

1
5


In [68]:
function f4(x, a)
  return x + a
end

a = 5
println(f4(1, a)) #a를 인풋으로 넣어준다고 명시했으므로 쇽 잘 들어간다.
println(a)

6
5


~~책에서는 밑에거는 안된다 했는데.. 된다..?~~

In [72]:
a = [1 2 3 4 5]
s = 0
for i in 1:length(a)
  s += a[i]
end
s

15

In [70]:
function my_sum(a)
  s = 0
  for i in 1:5
    s += a[i]
  end
  return s
end

a = [1; 2; 3; 4; 5]
my_sum(a)

15

## 3.8 Random Number Generation

statistic 함수들을 알아보자!

In [74]:
function my_randn(n, mu, sigma)
  return randn(n) .* sigma .+ mu
end

my_randn(10, 50, 3)

10-element Array{Float64,1}:
 55.60607682571125 
 51.18967165084307 
 41.24298827903912 
 48.29426171681405 
 49.44508983782427 
 52.152303605114135
 50.13654446099786 
 53.90228956685851 
 49.05312079354904 
 51.46882676643043 

In [76]:
#using Pkg
#Pkg.add("StatsFuns")
using StatsFuns

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Rmath ────────────── v0.6.0
 Installed Tables ───────────── v1.0.4
 Installed Mustache ─────────── v1.0.2
 Installed Parsers ──────────── v1.0.1
 Installed DataStructures ───── v0.17.12
 Installed MutableArithmetics ─ v0.2.9
 Installed ForwardDiff ──────── v0.10.10
 Installed StatsFuns ────────── v0.9.4
  Updating `~/.julia/environments/v1.1/Project.toml`
  [4c63d2b9] + StatsFuns v0.9.4
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [864edb3b] ↑ DataStructures v0.17.10 ⇒ v0.17.12
  [f6369f11] ↑ ForwardDiff v0.10.9 ⇒ v0.10.10
  [ffc61752] ↑ Mustache v1.0.0 ⇒ v1.0.2
  [d8a4904e] ↑ MutableArithmetics v0.2.7 ⇒ v0.2.9
  [69de0a69] ↑ Parsers v0.3.12 ⇒ v1.0.1
  [79098fc4] + Rmath v0.6.0
  [4c63d2b9] + StatsFuns v0.9.4
  [bd369af6] ↑ Tables v0.2.11 ⇒ v1.0.4
  Building Rmath → `~/.julia/packages/Rmath/BoBag/deps/build.log`


┌ Info: Precompiling StatsFuns [4c63d2b9-4356-54db-8cca-17b64c39e42c]
└ @ Base loading.jl:1186


In [79]:
mu = 50; sigma = 3;
println(normpdf(mu, sigma, 52)) # The probability density function (PDF) value evaluated at 52
println(normcdf(mu, sigma, 50))# The cumulative distribution function (CDF) value evaluated at 50
println(norminvcdf(mu, sigma, 0.5))# The inverse of CDF for probability 0.5

0.10648266850745075
0.5
50.0


In [81]:
## 3.9 File Input / Output
datafilename = "data.txt"
datafile = open(datafilename)
data = readlines(datafile)
close(datafile)
data

3-element Array{String,1}:
 "This is the first line." 
 "This is the second line."
 "This is the third line." 

In [82]:
for line in data
  println(line)
  # process each line here...
end

This is the first line.
This is the second line.
This is the third line.


In [89]:
outputfilename = "results1.txt"
outputfile = open(outputfilename, "w")
print(outputfile, "Magic Johnson")
println(outputfile, " is a basketball player.")
println(outputfile, "Michael Jordan is also a basketball player.")
close(outputfile)

outputfilename = "results2.txt"
outputfile = open(outputfilename, "a")
#output = open("results1.txt")
#println(outputfile, output)
println(outputfile, "Yuna Kim is a figure skating player.")
close(outputfile)

### read csv

In [92]:
using DelimitedFiles
csvfilename = "data.csv"
csvdata = readdlm(csvfilename, ',', header=true)
data = csvdata[1]
header = csvdata[2]
print(header)
data

AbstractString["start node" "end node" "link length"]

5×3 Array{Float64,2}:
 1.0  2.0  2.0
 1.0  3.0  4.5
 2.0  3.0  6.0
 2.0  4.0  3.0
 3.0  4.0  5.0

In [93]:
start_node = round.(Int, data[:,1])

5-element Array{Int64,1}:
 1
 1
 2
 2
 3

In [94]:
 end_node = round.(Int, data[:,2])

5-element Array{Int64,1}:
 2
 3
 3
 4
 4

In [95]:
link_length = data[:,3]

5-element Array{Float64,1}:
 2.0
 4.5
 6.0
 3.0
 5.0

In [96]:
value1 = [1.4; 3.1; 5.3; 2.7]
value2 = [4.3; 7.0; 3.6; 6.2]
resultfile = open("result.csv", "w")
println(resultfile, "node, first value, second value")
for i in 1:length(value1)
  println(resultfile, "$i, $(value1[i]), $(value2[i])")
end
close(resultfile)

In [99]:
using Pkg
Pkg.add("PyPlot")
using PyPlot

 Resolving package versions...
 Installed Reexport ───── v0.2.0
 Installed MacroTools ─── v0.5.5
 Installed LaTeXStrings ─ v1.1.0
 Installed PyCall ─────── v1.91.4
 Installed PyPlot ─────── v2.9.0
 Installed ColorTypes ─── v0.10.0
 Installed Colors ─────── v0.12.0
  Updating `~/.julia/environments/v1.1/Project.toml`
  [d330b81b] + PyPlot v2.9.0
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [3da002f7] + ColorTypes v0.10.0
  [5ae59095] + Colors v0.12.0
  [53c48c17] + FixedPointNumbers v0.8.0
  [b964fa9f] + LaTeXStrings v1.1.0
  [1914dd2f] + MacroTools v0.5.5
  [438e738f] + PyCall v1.91.4
  [d330b81b] + PyPlot v2.9.0
  [189a3867] + Reexport v0.2.0
  Building PyCall → `~/.julia/packages/PyCall/zqDXB/deps/build.log`


┌ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1186
┌ Warning: Module Conda with build ID 2170011602138119 is missing from the cache.
│ This may mean Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Conda with build ID 2170011602138119 is missing from the cache.
│ This may mean Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1186
┌ Warning: Module Conda with build ID 2170011602138119 is missing from the cache.
│ This may mean Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Info: Precompiling MacroTools [1914dd2f-81c6-5fcd-8719-6d5c9610ff09]
└ @ Base loading.jl:1186
┌ Info

In [100]:
using PyPlot

# Preparing a figure object
fig = figure()

# Data
x = range(0, stop=2*pi, length=1000)
y = sin.(3*x)

# Plotting with linewidth and linestyle specified
plot(x, y, color="blue", linewidth=2.0, linestyle="--")

# Labeling the axes
xlabel(L"value of $x$")
ylabel(L"\sin(3x)")

# Title
title("Test plotting")

# Save the figure as PNG and PDF
savefig("plot1.png")
savefig("plot1.pdf")

# Close the figure object
close(fig)

In [101]:
using PyPlot

# Data
lower_bound = [4.0, 4.2, 4.4, 4.8, 4.9, 4.95, 4.99, 5.00]
upper_bound = [5.4, 5.3, 5.3, 5.2, 5.2, 5.15, 5.10, 5.05]
iter = 1:8

# Creating a new figure object
fig = figure()

# Plotting two datasets
plot(iter, lower_bound, color="red", linewidth=2.0, linestyle="-",
 marker="o", label=L"Lower Bound $Z^k_L$")
plot(iter, upper_bound, color="blue", linewidth=2.0, linestyle="-.",
 marker="D", label=L"Upper Bound $Z^k_U$")

# Labeling axes
xlabel(L"iteration clock $k$", fontsize="xx-large")
ylabel("objective function value", fontsize="xx-large")

# Putting the legend and determining the location
legend(loc="upper right", fontsize="x-large")

# Add grid lines
grid(color="#DDDDDD", linestyle="-", linewidth=1.0)
tick_params(axis="both", which="major", labelsize="x-large")

# Title
title("Lower and Upper Bounds")

# Save the figure as PNG and PDF
savefig("plot2.png")
savefig("plot2.pdf")

# Closing the figure object
close(fig)

In [102]:
using PyPlot

# Data
data = randn(100) # Some Random Data
nbins = 10        # Number of bins

# Creating a new figure object
fig = figure()

# Histogram
plt[:hist](data, nbins)

# Title
title("Histogram")

# Save the figure as PNG and PDF
savefig("plot3.png")
savefig("plot3.pdf")

# Closing the figure object
close(fig)

┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
│   caller = top-level scope at In[102]:9
└ @ Core In[102]:9
